news_feed/urls.py
from django.urls import path
from . import views
app_name = 'news_feed'

urlpatterns = [
	#news_feed/
    path(r'', views.IndexView.as_view(), name = 'index'),

    #news_feed/sources/
    path(r'sources/', views.SourceView.as_view(), name = 'sources'),

    #news_feed/everything
    path(r'everything/', views.EverythingView.as_view(), name = 'everything'),
	
	#news_feed/top-headlines
	path(r'top-headlines/', views.TopHeadLinesView.as_view(), name = 'topheadlines')
    ]


newsfeed/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns
from news_feed.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news_feed/', include('news_feed.urls')),
]

news_feed/models.py
from django.db import models
import datetime


class TopHeadlines(models.Model):
    name = models.CharField(max_length=50)
    author = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=500)
    url = models.CharField(max_length=200)
    urlToImage = models.CharField(max_length=500, null=True)
    publishedAt = models.DateTimeField('date_published')
    content = models.CharField(max_length=1000)

    class Meta:
            unique_together = ("name", "description", "url", "urlToImage", "publishedAt")

    def __str__(self):
        return self.description + ',' + str(self.publishedAt)

    def jsonToNewsModel(self, jsonData,i):
        # i=0
        # print (1)
        news = News()
        category = Categories.objects.get(pk='id')
        news.model = category
        news.name = jsonData['articles'][i]['source']['name']
        news.description = jsonData['articles'][i]['description']
        news.url = jsonData['articles'][i]['url']
        news.urlToImage = jsonData['articles'][i]['urlToImage']
        news.publishedAt = jsonData['articles'][i]['publishedAt']
        # print (i)
        return news
        i=i+1

class Everything(models.Model):
    name = models.CharField(max_length=50)
    author = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=500)
    url = models.CharField(max_length=200)
    urlToImage = models.CharField(max_length=500, null=True)
    publishedAt = models.DateTimeField('date_published')
    content = models.CharField(max_length=1000)

    class Meta:
            unique_together = ("name", "description", "url", "urlToImage", "publishedAt")

    def __str__(self):
        return self.description + ',' + str(self.publishedAt)

class Sources(models.Model):
    # id = models.CharField(max_length=50)
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    url = models.CharField(max_length=100)
    category = models.CharField(max_length=50)
    language = models.CharField(max_length=10)
    country = models.CharField(max_length=10)


    def jsonToSourcesModel(selfself, jsonData, i):
        source = Sources()
        # source.id = jsonData['sources'][i]['id']
        source.name = jsonData['sources'][i]['name']
        source.description = jsonData['sources'][i]['description']
        source.url = jsonData['sources'][i]['url']
        source.category = jsonData['sources'][i]['category']
        source.language = jsonData['sources'][i]['language']
        source.country = jsonData['sources'][i]['country']

        return source

    def __str__(self):
        return self.language + ',' + str(self.name)+','+self.category


    class Meta:
            unique_together = ("name", "description", "url", "category", "language")

news_feed/forms.py
from django.contrib.auth.models import User
from django import forms


class SourceForm(forms.Form):
    category_selected = forms.BooleanField(required=False)
    language_selected = forms.BooleanField(required=False)
    country_selected = forms.BooleanField(required=False)


class EverythingForm(forms.Form):
    q = forms.CharField(max_length=100, required=False)
    domains = forms.CharField(max_length=100, required=False)
    fromTime = forms.DateField(required=False)
    toTime = forms.DateField(required=False)
    language_selected = forms.BooleanField(required=False)
    sortBy = forms.ChoiceField(widget=forms.RadioSelect, required=False)
    
    
class TopHeadLinesForm(forms.Form):
    q = forms.CharField(max_length=100, required=False)
    country = forms.BooleanField(required=False)
    category = forms.BooleanField(required=False)
    
    # class Meta:
    #     model = User
    #     fields = ['language', 'country', 'category']
#

news_feed/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from news_feed.models import Everything, Sources
from news_feed.serializers import NewsFeedSerializer
from newsfeed import settings
import requests
from .forms import SourceForm, EverythingForm
import json
from newsapi import NewsApiClient
# Create your views here.

class IndexView(ListView):
    template_name = 'news_feed/index.html'

    def get_queryset(self):
        return self.template_name

    # context_object_name = 'all_news'
    
class TopHeadLinesView(DetailView):
    form  = TopHeadLineForm
    url=''
    def get(self, request):
        form = self.form(None)
        self.url = 'https://newsapi.org/v2/top-headlines?'
        return render(request, 'news_feed/topheadlines.html', {'form':form})

    def post(self, request):
        form = self.form(request.POST)
        print (form)
        if form.is_valid():
            # user = form.save(commit=False)
            # print ("hi")
            self.url = 'https://newsapi.org/v2/top-headlines?'
            query = form.cleaned_data['q']
            domains = form.cleaned_data['domains']
            country = form.cleaned_data['country']
            category = form.cleaned_data['category']
            sortBy = request.POST.get('radio', None)
            print (type(query),domains,fromDate,toDate,sortBy)
            if query!='':
                self.url = self.url+'q="'+query+'"&'
#             if domains!='':
#                 self.url = self.url+'domains='+domains+'&'
            if country!=None:
                self.url = self.url+'country='+country+'&'
            if category!=None:
                self.url = self.url+'category='+category+'&'
#             if sortBy!=None:
#                 self.url = self.url+'sortBy='+sortBy+'&'
            self.url = self.url+'apiKey='+settings.API_KEY
            print (self.url)
            r = requests.get(self.url)
            jso = r.json()
            return render(request, 'news_feed/topheadlines.html', {'source': source, 'form': form, 'jso':jso},)
            
class EverythingView(DetailView):
    form  = EverythingForm
    url=''
    def get(self, request):
        form = self.form(None)
        self.url = 'https://newsapi.org/v2/everything?'
        return render(request, 'news_feed/everything.html', {'form':form})

    def post(self, request):
        form = self.form(request.POST)
        print (form)
        if form.is_valid():
            # user = form.save(commit=False)
            # print ("hi")
            self.url = 'https://newsapi.org/v2/everything?'
            query = form.cleaned_data['q']
            domains = form.cleaned_data['domains']
            fromDate = form.cleaned_data['fromTime']
            toDate = form.cleaned_data['toTime']
            sortBy = request.POST.get('radio', None)
            print (type(query),domains,fromDate,toDate,sortBy)
            if query!='':
                self.url = self.url+'q="'+query+'"&'
            if domains!='':
                self.url = self.url+'domains='+domains+'&'
            if fromDate!=None:
                self.url = self.url+'from='+str(fromDate)+'&'
            if toDate!=None:
                self.url = self.url+'to='+str(toDate)+'&'
            if sortBy!=None:
                self.url = self.url+'sortBy='+sortBy+'&'
            self.url = self.url+'apiKey='+settings.API_KEY
            print (self.url)
            r = requests.get(self.url)
            jso = r.json()
            print (jso)
            return render(request, 'news_feed/everything.html', {'source': source, 'form': form, 'jso':jso},)

class SourceView(DetailView):
    form = SourceForm

    def get(self, request):
        form = self.form(None)
        source = Sources()
        r = requests.get('https://newsapi.org/v2/sources?apiKey='+settings.API_KEY)
        jso = r.json()
        i=0

        while (i<len(jso['sources'])):
            try:
                # print (jso)
                m = source.jsonToSourcesModel(jso,i)
                m.save()
                i+=1
            except:
                i+=1
        q = Sources.objects.all()
        return render(request, 'news_feed/sources.html', {'source': source, 'form': form, 'q':q},)

    def post(self, request):
    
        form = self.form(request.POST)
        if form.is_valid():

            q = Sources.objects.all()
            print (request.POST.getlist('category_tag[]', False))
            if request.POST.getlist('category_tag[]', False):

                category_tag = request.POST.getlist('category_tag[]')
                print (category_tag)
                q = q.filter(category__in=category_tag)
                
            print (request.POST.get('lang_tag[]', False))
            if request.POST.get('lang_tag[]', False):
                lang_tag = request.POST.getlist('lang_tag[]')
                print (lang_tag)

                q = q.filter(language__in=lang_tag)
                

            if request.POST.get('country_tag[]', False):
        
                country_tag = request.POST.getlist('country_tag[]')
                print (country_tag)

                q = q.filter(country__in=country_tag)

            if q==[]:
                return render(request,'news_feed/sources.html', {'q': None})
            else:
                return render(request, 'news_feed/sources.html', {'q': q})


            # print (i)




news_feed/templates/news_feed/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}News{% endblock %}</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Satisfy">
	<link rel="stylesheet" type="text/css" href="{% static 'news_feed/style.css' %}"/>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>



</head>
<body>

	<nav class="navbar navbar-inverse">
		<div class="container-fluid">

			<!-- Header -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target = "#topNavBar">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class= "navbar-brand" href="{% url 'news_feed:index' %}">News</a>
			</div>

			<!-- Items -->
			<div class="collapse navbar-collapse" id="topNavBar">
				<ul class="nav navbar-nav navbar-right">
					<li class="">
						<a href="{% url 'news_feed:index' %}">
							<span class="glyphicon glyphicon-cd" aria-hidden = "true"></span>&nbsp;
							Top Headlines
						</a>
					</li>

					<li class="">
						<a href="{% url 'news_feed:everything' %}">
							<span class="glyphicon glyphicon-music" aria-hidden = "true"></span>&nbsp;
							Everything
						</a>
					</li>

					<li class="">
						<a href="{% url 'news_feed:sources' %}">
							<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
							Sources
						</a>
					</li>
                </ul>
				<!--<form class="navbar-form navbar-left" role = "search" method="get" action="#">-->
					<!--<div class="form-group">-->
						<!--<input type="text" class="form-control" name="q" value="">-->
					<!--</div>-->
					<!--<button type="submit" class="btn btn-default">Search</button>-->
				<!--</form>-->
            </div>
		</div>
        <div class="header">
    <div class="progress-container">
    <div class="progress-bar" id="myBar"></div>
  </div>
    </div>
	</nav>
	<!--Scroll indicator-->

</div>

<script>

window.onscroll = function() {myFunction()};
    function myFunction() {
  var winScroll = document.body.scrollTop || document.documentElement.scrollTop;
  var height = document.documentElement.scrollHeight - document.documentElement.clientHeight;
  var scrolled = (winScroll / height) * 100;
  document.getElementById("myBar").style.width = scrolled + "%";
}
</script>

	{% block body %}
	{% endblock %}
</body>
</html>

news_feed/templates/news_feed/everything.html
{% extends 'news_feed/base.html'%}
{% block title %}Sources{% endblock %}
{% block body %}

<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12 col-md-7">
			<div class="panel panel-default">
				<div class="panel-body">
					<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
						{% csrf_token %}
                        Search&nbsp;
                        <input type="text" name="q">
                        <br><br>
                        Domain&nbsp;
                        <input type="text" name="domains">
                        <br><br>
                        From&nbsp;
                        <input type="date" name="fromTime">&nbsp;&nbsp;
                        To&nbsp;
                        <input type="date" name="toTime">
                        <br><br>
                        Sort According to<br>
                        <input type="radio" name="radio" value="publishedAt">Published Date<br>
                        <input type="radio" name="radio" value="relevancy">Search input<br>
                        <input type="radio" name="radio" value="popularity">Popularity<br>
                        <br>
                        <input type="submit" name="submit">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

news_feed/templates/news_feed/index.html
{% extends 'news_feed/base.html'%}
{% block body %}

<div class="mainindex">
<!-- Slideshow container -->
<div class="slideshow-container">
  <!-- Full-width images with number and caption text -->
    <div class="mySlides">
    <!--<div class="numbertext">1 / 3</div>-->
    <img src="/static/news_feed/images/Reading-Newspaper.jpg" style="width:100%">
    <div class="text">Get details about latest trends in the market</div>
  </div>

  <div class="mySlides">
    <!--<div class="numbertext">2 / 3</div>-->
    <img src="/static/news_feed/images/Technology.jpg" style="width:100%">
    <div class="text">Get news about technology, sports and politics</div>
  </div>

  <div class="mySlides">
    <!--<div class="numbertext">3 / 3</div>-->
    <img src="/static/news_feed/images/financial.jpg" style="width:100%">
    <div class="text">Various sources of news around the world to provide you with better insights about the world</div>
  </div>

  <!-- Next and previous buttons -->
  <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
  <a class="next" onclick="plusSlides(1)">&#10095;</a>
</div>
<br>

<!-- The dots/circles -->
<div style="text-align:center">
  <span class="dot" onclick="currentSlide(1)"></span>
  <span class="dot" onclick="currentSlide(2)"></span>
  <span class="dot" onclick="currentSlide(3)"></span>
</div>



<div>
  hello
</div>
<br>
<br>
<div>
  hi
</div>
    <br>
<br>
<div>
  hi
</div>
</div>
<!--Script for Slideshow-->
<script>
var slideIndex = 1;
showSlides(slideIndex);

// Next/previous controls
function plusSlides(n) {
  showSlides(slideIndex += n);
}

// Thumbnail image controls
function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  var i;
  var slides = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("dot");
  if (n > slides.length) {slideIndex = 1}
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";
  }
  for (i = 0; i < dots.length; i++) {
      dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";
  dots[slideIndex-1].className += " active";
}
</script>



<!--Script for Scroll indicator-->
<!--<script>-->
    <!--window.onscroll = function() {myFunction()};-->

<!--function myFunction() {-->
  <!--var winScroll = document.body.scrollTop || document.documentElement.scrollTop;-->
  <!--var height = document.documentElement.scrollHeight - document.documentElement.clientHeight;-->
  <!--var scrolled = (winScroll / height) * 100;-->
  <!--document.getElementById("myBar").style.width = scrolled + "%";-->
<!--}-->

</script>
{% endblock %}

news_feed/templates/news_feed/sources.html
{% extends 'news_feed/base.html'%}
{% block title %}Sources{% endblock %}
{% block body %}


<ul >
    <form action="", method="post">
        {% csrf_token %}
        <div class="main">
        <label>Category</label>

        <div>
        <input type="checkbox", name="category_tag[]", value="entertainment">Entertainment
        <input type="checkbox", name="category_tag[]", value="business">Business
        <input type="checkbox", name="category_tag[]", value="general">General
        <input type="checkbox", name="category_tag[]", value="health">Health
        <input type="checkbox", name="category_tag[]", value="sports">Sports
        <input type="checkbox", name="category_tag[]", value="science">Science
        <input type="checkbox", name="category_tag[]", value="technology">Technology
        <br>
        <br>
        </div></div>
        <div>
    <label>Language</label>
        <div>
        <input type="checkbox", name="lang_tag[]", value="ar">Arabic
        <input type="checkbox", name="lang_tag[]", value="de">German
        <input type="checkbox", name="lang_tag[]", value="en">English
        <input type="checkbox", name="lang_tag[]", value="es">Spanish
        <input type="checkbox", name="lang_tag[]", value="fr">French
        <input type="checkbox", name="lang_tag[]", value="he">Hebrew
        <input type="checkbox", name="lang_tag[]", value="it">Italian
        <input type="checkbox", name="lang_tag[]", value="nl">Dutch
        <input type="checkbox", name="lang_tag[]", value="no">Norwegian
        <input type="checkbox", name="lang_tag[]", value="pt">Portuguese
        <input type="checkbox", name="lang_tag[]", value="ru">Russian
        <input type="checkbox", name="lang_tag[]", value="se">Swedish
        <input type="checkbox", name="lang_tag[]", value="ud">Urdu
        <input type="checkbox", name="lang_tag[]", value="zh">Chinese
        <br>
        <br>
        </div>
        </div>
        <div>
        <label>Country</label>
        <div>
        <input type="checkbox", name="country_tag[]", value="ae">United Arab Emirates
        <input type="checkbox", name="country_tag[]", value="ar">Argentina
        <input type="checkbox", name="country_tag[]", value="at">Austria
        <input type="checkbox", name="country_tag[]", value="au">Australia
        <input type="checkbox", name="country_tag[]", value="be">Belgium
        <input type="checkbox", name="country_tag[]", value="bg">Bulgaria
        <input type="checkbox", name="country_tag[]", value="br">Brazil
        <input type="checkbox", name="country_tag[]", value="ca">Cananda
        <input type="checkbox", name="country_tag[]", value="ch">Switzerland
        <input type="checkbox", name="country_tag[]", value="cn">China
        <input type="checkbox", name="country_tag[]", value="co">Colombia
        <input type="checkbox", name="country_tag[]", value="cu">Cuba
        <input type="checkbox", name="country_tag[]", value="cz">Czech Republic
        <input type="checkbox", name="country_tag[]", value="de">Germany
        <input type="checkbox", name="country_tag[]", value="eg">Egypt
        <input type="checkbox", name="country_tag[]", value="fr">France
        <input type="checkbox", name="country_tag[]", value="gb">English
        <input type="checkbox", name="country_tag[]", value="gr">Greece
        <input type="checkbox", name="country_tag[]", value="hk">Hong Kong
        <input type="checkbox", name="country_tag[]", value="hu">Hungary
        <input type="checkbox", name="country_tag[]", value="id">Indonesia
        <input type="checkbox", name="country_tag[]", value="ie">Ireland
        <input type="checkbox", name="country_tag[]", value="il">Israel
        <input type="checkbox", name="country_tag[]", value="in">India
        <input type="checkbox", name="country_tag[]", value="it">Italy
        <input type="checkbox", name="country_tag[]", value="jp">Japan
        <input type="checkbox", name="country_tag[]", value="kr">South Korea
        <input type="checkbox", name="country_tag[]", value="lt">Lithuania
        <input type="checkbox", name="country_tag[]", value="lv">Latvia
        <input type="checkbox", name="country_tag[]", value="ma">Morocco
        <input type="checkbox", name="country_tag[]", value="mx">Mexico
        <input type="checkbox", name="country_tag[]", value="my">Malaysia
        <input type="checkbox", name="country_tag[]", value="ng">Nigeria
        <input type="checkbox", name="country_tag[]", value="nl">Netherlands
        <input type="checkbox", name="country_tag[]", value="no">Norway
        <input type="checkbox", name="country_tag[]", value="nz">New Zealand
        <input type="checkbox", name="country_tag[]", value="ph">Norwegian
        <input type="checkbox", name="country_tag[]", value="pl">Philippines
        <input type="checkbox", name="country_tag[]", value="pt">Portugal
        <input type="checkbox", name="country_tag[]", value="ro">Romania
        <input type="checkbox", name="country_tag[]", value="rs">Serbia
        <input type="checkbox", name="country_tag[]", value="ru">Russia
        <input type="checkbox", name="country_tag[]", value="sa">Saudi Arabia
        <input type="checkbox", name="country_tag[]", value="se">Swedwn
        <input type="checkbox", name="country_tag[]", value="sg">Singapore
        <input type="checkbox", name="country_tag[]", value="si">Slovenia
        <input type="checkbox", name="country_tag[]", value="sk">Slovakia
        <input type="checkbox", name="country_tag[]", value="th">Thailand
        <input type="checkbox", name="country_tag[]", value="tr">Turkey
        <input type="checkbox", name="country_tag[]", value="tw">Taiwan
        <input type="checkbox", name="country_tag[]", value="ua">Ukraine
        <input type="checkbox", name="country_tag[]", value="us">United States
        <input type="checkbox", name="country_tag[]", value="ve">Venezuela
        <input type="checkbox", name="country_tag[]", value="za">South Africa

        <br>
        <br>
        </div>
        </div>
        <input type="submit" value="Submit" name="Submit">

    </form>
</ul>
{%if q%}
    {% for value in q %}
        <ul>{{value.description}}</ul>
    {% endfor %}
{%else%}
    <ul><b><strong>No sources to display</strong></b></ul>
{%endif%}
{% endblock %}